#!/bin/bash

a=$( xrandr --listmonitors |grep -o HDMI...... )
d1=$(echo $a | cut -c1-5)
r1=$(echo $a | cut -c7-10)
d2=$(echo $a | cut -c12-16)
r2=$(echo $a | cut -c18-21)

if [ $r1 -eq "1920" ];then
	xrandr --output $d2 --off
	xrandr --output $d2 --auto --right-of $d1
elif [ $r2 -eq "1920" ];then
	xrandr --output $d1 --off
	xrandr --output $d1 --auto --right-of $d2
else
	echo error
fi
